### PR TITLE
Re-run smithy against the 3.x branch to try and catch the py 3.11 builds

### LINKED ISSUE #26: Python 3.11 package missing for 3.1 LTS
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

There's currently no pymbar 3.1 LTS cf package for Python 3.11 available.

Would you be able to create one @mikemhenry ?

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

### PR DESCRIPTION
**Pull request by Lnaden**
Will eventually Fix #26 

So far, this doesn't snag the 3.11 python builds when I build locally, so maybe the bot here will do better.

MNT: Re-rendered with conda-build 3.22.0, conda-smithy 3.21.3, and conda-forge-pinning 2022.11.08.10.32.09

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Lnaden** [comment]
@conda-forge-admin please rerender

**Comment by mikemhenry** [comment]
@Lnaden Thanks for getting to this so quickly!

**Comment by mikemhenry** [comment]
Just need to figure out how to get the bot to run on this branch or do the migration manually

**Comment by mikemhenry** [comment]
Not sure if this was the right way but I copied the migration file from https://github.com/conda-forge/pymbar-feedstock/pull/25/commits/9d0acf4807045147eda6b8dfddb7c177f37a32b7 and re-rendered the PR

**Comment by mikemhenry** [comment]
@jaimergp is that the correct procedure?

**Pull request merged**
