### PR TITLE
Add @jaimergp as a maintainer

### PR DESCRIPTION
**Pull request by jchodera**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jchodera** [comment]
@conda-forge-admin, please rerender

**Comment by jchodera** [comment]
Tagging @jaimergp

**Comment by jaimergp** [comment]
You can add the label `automerge` to let the bot merge when CI succeeds. I'll take over when that happens!

**Review by Lnaden — APPROVED** [review]

**Comment by jchodera** [comment]
@jaimergp: Looks like I was too late with the label, so I've merged this manually.

**Comment by jaimergp** [comment]
All good!

**Pull request merged**
