### PR TITLE
Unpin numpy

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by jschueller** [comment]
@ocefpaf this one too ?

**Comment by ocefpaf** [comment]
You are a PR machine @jschueller :wink: 

Thanks for all the updates!

**Comment by Lnaden** [comment]
Thanks. Is there a change to the conda-forge deployment which needed this change? And is there anything you need me to do as the package maintainer?

**Comment by ocefpaf** [comment]
> Thanks. Is there a change to the conda-forge deployment which needed this change?

Yes, we updated how we build packages that depends on `numpy`. See https://conda-forge.org/docs/meta.html#building-against-numpy

> And is there anything you need me to do as the package maintainer?

This change is not mandatory but it is nice to have b/c it removes the burden on the CIs building the extension once and running against multiple numpy versions. So in the long term it is nice if all the maintainers implement that.

**Pull request merged**
