### PR TITLE
Only require jax but constrain jaxlib

### PR DESCRIPTION
**Pull request by mattwthompson**
A little #32, a little #31. https://github.com/conda-forge/pymbar-feedstock/issues/30#issuecomment-1468343120

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by mikemhenry** [comment]
@Lnaden How does this look?

**Comment by mikemhenry** [comment]
Tested locally and it works! Going to see if I can figure out the artifact upload issue, if not we will just turn that off and the builds should be fine.

**Comment by mikemhenry** [comment]
@Lnaden Let me know if you are happy with this and we can get it merged in (or if you are so inclined, you can hit the merge button)

**Comment by Lnaden** [comment]
@conda-forge-admin, please rerender

**Comment by Lnaden** [comment]
I am happy with this, sorry its taken me a bit to circle back to this.

**Pull request merged**
